### ISSUE TITLE
[FEATURE] Features

### ISSUE THREAD

**Issue by YashSoPro** [Unofficial-Life/Lawnchair-Modded#20]
### Checklist

- [x] No one has submitted a similar or identical bug report before.
- [ ] Please check if the same issue is presented in [the upstream nightly artifact](https://github.com/LawnchairLauncher/lawnchair/releases/tag/nightly). If so, please file the issue to that repository instead.

### Describe the bug

i would love if you added new features even in original lawn-chair since 12 version nothing has changed too much

**Comment by Unofficial-Life** [comment]
@YashSoPro Beta 3 has the biggest change with all new monet system, now when A15 will be merged to lawnchair they will add few more things

**Comment by YashSoPro** [comment]
> @YashSoPro Beta 3 has the biggest change with all new monet system, now when A15 will be merged to lawnchair they will add few more things

okk im on android 11 i guess but i suggest there is a root settings for quickswitch and im not rooted you guys can add something that works with shizuku

**Comment by Unofficial-Life** [comment]
@YashSoPro I am not a coder per say, I am just a normal person interested in few things and do what I can understand. 

I am also using A11 and you can still use monet on the lawnchair, about quickswitch it can't be done with shizuku because it needs system level permission to change recents and call upon animation api's
